global class BWPS_Constants {
         public static String BWPS_instructorRecordType='Instructor Record Type';
         public static String BWPS_guestUserRecordType='Guest User Record Type';
         public static String BWPS_clientRecordType='Client Record Type';
        global static String RecurringDonationRecordType = 'Recurring Class';
        global static String OneTimeDonationRecordType = 'One Time Class'; 
        global static String InstructorRecordType = 'Instructor Record Type'; 
        global static String BWPS_DonorRecordType = 'Donar Record Type'; 
        global static String BWPS_MembershipRecordType = 'Membership'; 

}