import { LightningElement , track, wire, api} from 'lwc';
import heroImage from '@salesforce/resourceUrl/PrivacyHeaderImage';

export default class Bwps_Privacy extends LightningElement {
  heroImage = heroImage;
    privacyData = `<div><h2 style=\"text-align: center\"><p style=\"font-size: 2rem;\"><strong>PARKINSON FOUNDATION OF THE NATIONAL CAPITAL AREA</strong><br /><p/>
    <p>(also d/b/a ParkinsonFoundation.Org)</p>
<h2 style=\"text-align: center;margin-bottom: 0rem;\">Privacy Policy – Version of May 2023</h2>
<p>Hello! You have arrived at the Privacy Policy (this “Policy”) of Parkinson Foundation of the National Capital Area (“PFNCA”), a 501(c)(3) nonprofit organization (status pending) dedicated to assisting and supporting persons with Parkinson’s. In this Policy, forms of the pronoun “we” refer to PFNCA, and forms of the pronoun “you” refer to you, the user reading this Policy.</p>
<p style=\"text-indent: 4em;\">PFNCA supports the maintenance of the privacy of information that can be linked to a specific individual, such as a name, postal address, telephone number(s), email address, and the like (such information that we may collect from you on the Site, “Personal Info”). This Policy describes our privacy practices and how we use information gathered at or through our websites at <a href="http://parkinsonfoundation.org">http://parkinsonfoundation.org</a> and <a href="http://pfnca.org">http://pfnca.org</a> as well as when you use social media that overlaps PFNCA’s social media or website (such websites, social media, and any services, activities, transactions, or the like provided through them, collectively, the "Site") and when you sign for classes or otherwise engage in other activities or transactions with PFNCA (such classes and activities, “Activities”). This policy does not apply to information PFNCA may collect or purchase from other sources. By visiting or using the Site, engaging in Activities, or submitting Personal Info through or at the Site or otherwise to PFNCA, you agree to the terms of this Policy as it is in effect at the time of your visit as well as the terms of our Waiver and Rules of Participation (the “Rules”) (which can be found here <a href="https://parkinsonfoundation.org/pfnca-online-wellness-classes-waiver-and-rules-of-particiation">https://parkinsonfoundation.org/pfnca-online-wellness-classes-waiver-and-rules-of-particiation</a>). If you do not agree to the terms and conditions of this Policy, you must not visit the Site, engage in Activities, or submit any Personal Info to PFNCA. This Policy will be updated periodically, so please be sure to reread it from time to time.</p> <br/>
<h2 style=\"margin-bottom: 0rem;\">Information We Collect</h2>
<p>We collect information on you in various ways, including through voluntary submissions, your participation in Activities, and transactions through or at the Site, and through cookie and other tracking technology. We collect the following types of information:</p>
<ul>
  <li><strong>Personal Info.</strong> We may collect Personal Info to the extent needed to interact with you, which may include registration information, transaction-related information (including information provided when you donate (a person who so donates, a “Donor’), information you provide us when you contact us for support, credit card information (if the Site has been enabled to accept payments to us directly), phone numbers, and the like. Credit card information may be collected by a third-party site, whose information you may see when you submit payment information. We do not control how that third-party, or any third-party, may use your Personal Info. A unique device identifier, such as a cookie, may also be automatically assigned to the device you use to access the Site, which could also be associated with other Personal Info. We treat that combined information as Personal Info in accordance with this Policy for as long as it is combined. If you use social media logins (like Google and Facebook) to log into the Site, we may access your social media profile information, a kind of sharing of Personal Info you can limit using your social media service settings. Please note that attendance or engagement in Activities may reveal your confidential information by virtue of your being identified. For instance, when you participate in a Zoom or in-person class your name is likely to be revealed to other participants. You consent to such disclosure by participating in the applicable Activity. Furthermore, while your engagement in Activities with PFNCA on its own might link you to a medical condition by implication, PFNCA is not providing health care services, does not gather protected health information, other than Personal Info, and does not knowingly engage in transactions covered by HIPAA and its related regulations.</li>
  <li><strong>Aggregate Info.</strong> “Aggregate Info” is non-Personal Info the Site may automatically collect and store indefinitely through the use of cookies, web beacons, or similar technologies, clear gifs, embedded scripts, ETags , and other tracking technologies (including those that may become available in the future), all of which may record information such as Internet domain and host names, protocol (IP) addresses, browser software and operating system types, clickstream patterns, MAC addresses or other device technical information, location information, and dates and times that the Site is accessed. Aggregate Info does not identify any individual person, but we may link Aggregate Information using tracking technologies to Personal Info we collect.</li>
</ul> 
<h2 style=\"margin-bottom: 0rem;\">With Whom We Share Information and How We Use It</h2> 
<p><strong>Personal Info.</strong>  - We may use Personal Info to accept donations from you, carry out and record Activities with you, improve our understanding of your interests, improve our services, contact you for future support, notify you of information, activities, events, fundraising, or the like that we think might interest you, permit you to utilize certain features of the Site or carry out Activities, respond to you, verify other information about you, or enforce rules concerning or monitor the use of the Site or of Activities. If you do submit Personal Info to us, we will use it for the purposes for which it was submitted. We may also use your Personal Info to contact you about other Activities and/or fundraising campaigns or as otherwise disclosed to you at the point of collection. We may also use your name, postal address, and telephone number(s) to contact you offline. To the extent you have created an account at the Site, we may use your log information to operate and assess the performance of the Site or other services, prevent fraud, provide technical support, and/or respond to your needs for you to engage in Activities. </p>
<p style=\"text-indent: 4em;\">For Donors, we use and store your Personal Info, including dates and amounts of donations, for record-keeping and reporting purposes as may be required by law, including to report such matters to the IRS. Such information may be retained and used by us indefinitely for such purposes. When you donate to PFNCA through the Site, we use the services of Stripe and Chargent (a product of AppFrontier) to collect the donations. As such, these services will also have access to the Personal Info you provide them when you donate. To understand how these services may use or share that Personal Info, please review their privacy policies at https://stripe.com/privacy  and https://appfrontier.com/privacy.</p>
<p style=\"text-indent: 4em;\">To the extent the Site collects or receives your Personal Info, our hosting service with Salesforce, may also have access to it. To understand how Salesforce may use or share your Personal Info, please review their privacy policy overview and other information at https://www.salesforce.com/privacy/overview.</p>
<p style=\"text-indent: 4em;\">We will not otherwise sell, transmit, or rent your email address to any third party, unless PFNCA has obtained the email address legally through independent means. From time to time, we may send out email messages that might include information about like-missioned organizations and companies, but we do not provide them with access to any Personal Information that you have provided.</p>
<p style=\"text-indent: 4em;\">PFNCA complies with those provisions of the CAN-SPAM Act applicable to charitable organizations. All email mailings from PFNCA will contain a link to unsubscribe from PFNCA emails.</p>
<p style=\"text-indent: 4em;\">PFNCA may use the Personal Info collected from you directly or through any of its third-party service providers to market PFNCA services and services provided by PFNCA’s partners, to provide PFNCA information to you, and to solicit donations and other assistance from you. If the system provides you with the ability to opt out of marketing communications, the system after such opt-out might not thereafter function as you expect or desire, and you may miss important information about your activities with PFNCA.</p>
<p style=\"text-indent: 4em;\">Other than as described in this Policy, or as may be necessary to protect the rights, property, and safety of our organization or others, or as may be necessary to comply with applicable law, and other than as described in this Policy, we will not give, transfer, or sell the Personal Info you provide us online.</p><br/>
<p><strong>Aggregate Info</strong> – PFNCA uses Aggregate Info to operate, maintain, assess, analyze, and improve the Site and Activities, personalize your Internet experience, analyze Site usage, create and provide services and/or products to fit your needs, offer or market products or services by us, our affiliates, or our third-party business partners, prevent fraud, provide technical and other support, conduct research, generate analytics, address internal operations, respond to your needs or requests, and the like. PFNCA owns all Aggregate Info, maintains copies of it as part of its record, and may share it with related entities, advertisers, sponsors, partners, and other third-party vendors. We may use or disclose Aggregate Info for any purpose. The majority of browsers accept cookies, but your browser may also give you options for preventing, accepting, or receiving notice of new cookies. Please be advised that if you block cookies, some Site functionality may be lost. </p>
<p style=\"text-indent: 4em;\">We also share information obtained through the use of Google Analytics with Google. To understand what data is collected through the use of Google Analytics on the Site and how Google uses it, please visit “How Google uses information from sites or apps that use our services” at https://policies.google.com/technologies/partner-sites. You can opt-out of Google Analytics without affecting how you visit our site – for more information on opting out of being tracked by Google Analytics across all websites you use, please visit:</p>
<p>https://tools.google.com/dlpage/gaoptout. Outside of the Google Analytics platform, PFNCA may use unique IDs to link Personal Info to Google Analytics data and, in such a case, will treat the combined information as Personal Info. </p><br/>
<h2 style=\"margin-bottom: 0rem;\">Third Party Websites and Links</h2>
<p>The Site may contain links to other sites operated by, and uses the services of, third parties, including those third-party services specifically identified in this Policy (all such third parties, “Third Parties”). We do not control such other sites or Third Parties and are not responsible for their content, their privacy policies, or their use of Personal Info. Inclusion of such links on, or use of a Third Party’s services by, the Site does not, by itself, imply any endorsement of the content on such sites or of their owners or operators except as otherwise expressly stated on the Site. While we support the protection of your privacy on the Internet, we expressly disclaim any and all liability for the actions or omissions of all Third Parties, including but without limitation those relating to their use and/or disclosure of Personal Info. Third Parties may collect Personal Info about your online activities over time and across different Web sites when you use the Site. The Site may also include embedded content (e.g. videos, images, articles, etc.). Embedded content from other websites behaves in the exact same way as if the visitor has visited the other Third Party’s website. These websites may collect data about you, use cookies, embed additional third-party tracking, and monitor your interaction with that embedded content, including tracking your interaction with the embedded content if you have an account and are logged in to that website.</p><br/>
<h2 style=\"margin-bottom: 0rem;\">YOUR POSTING AND MATERIALS</h2>
<p>Should we permit you to post or otherwise provide to us comments, materials, images, or any other information (collectively, “Your Materials”) on any of the Sites, you hereby grant us a non-forfeitable, royalty-free, paid-up, world-wide license to use such Your Materials so provided for all purposes related to the promotion, marketing, and operation of PFNCA, and you hereby guarantee to us that any of such, Your Materials so posted and such provision thereof do not infringe any intellectual property or likeness rights of any third-party. To the extent you provide us likenesses or messages to be included in communications made by us on your behalf (“Limited Use Materials”), such as a donation in somebody’s name or for their benefit, you grant us the same type of license in such Limited Use Materials as is granted for Your Materials in general, however, limited to a scope of use for such Limited Use Materials to use for those purposes.</p><br/>
<h2 style=\"margin-bottom: 0rem;\">Legal Process</h2>
<p>In the event we are required to respond to subpoenas, court orders or other legal process your Personal Info may be disclosed pursuant to such subpoena, court order, or legal process without notice to you.</p><br/>
<h2 style=\"margin-bottom: 0rem;\">Security</h2>
<p>Personal Info may be stored within databases controlled directly by us or through our service providers. As we deem appropriate and as may be required by applicable law, we employ security appropriate for the types of Personal Info consistent with industry standards. We also use industry standard encryption technology to protect credit card and password information to the extent we are collecting it and not a third party. However, no security system is infallible, and therefore we cannot guarantee the security of our databases nor that information you supply will not be intercepted while being transmitted to us over the Internet. Therefore, we shall not be liable to you under any circumstances for any inadvertent or unintentional disclosure of any information, including Personal Info, nor for any failure by any third-party provider to securely protect any Personal Info.</p>
<p style=\"text-indent: 4em;\">Your information may be transferred to, and maintained on, computers located outside of your place of residence where the privacy laws may not be as protective as those where you live. If you are located outside the United States and choose to provide information to us, you are hereby notified that we transfer, process, and store Personal Info in the United States. As a result, this information may be subject to access by governments, courts, law enforcement officials, and national security authorities in the United States according to its and its states’ laws. By submitting Personal Info, you consent to having it transferred to, processed, and stored in the United States. We may assign you a user ID and a password for full access to the Site. Your user ID and password may only be used by you and the members of your household. You may not share your user ID and password with anyone else, and you are solely responsible for maintaining and protecting the confidentiality of your user ID and password. You are fully responsible for all activities that occur under your user ID and password. </p><br/>
<h2 style=\"margin-bottom: 0rem;\">Privacy of Children</h2>
<p>The Site is not intended to be used by, and Activities are not intended for, anyone under the age of majority within the jurisdiction in which they reside without the supervision of a parent or guardian of majority age. An individual under the age of majority may use the Site or engage in Activities only with supervision of an adult parent or guardian. We do not seek or knowingly collect any Personal Info about children under 13 years of age. If we become aware that we have collected Personal Info from a child under the age of 13, we will make commercially reasonable efforts to delete such information from our database.</p><br/>
<h2 style=\"margin-bottom: 0rem;\">EU Citizens</h2>
<p>The site is not intended to be used by citizens of the European Union. However, if you are such a citizen and you use the Site despite this disclaimer (a) to the extent you donate, you will have expressly consented to the Policy and the use and return of your Personal Info as provided in this Policy for Donors, and (b) otherwise you may request us to delete your Personal Data by sending the request to pfnca@parkinsonfoundation.org  and we will locate and delete your Personal Data</p><br/>
<h2 style=\"margin-bottom: 0rem;\">Governing Law, Submission to Jurisdiction, Waiver of Rights </h2>
<p>This Policy, the Rules, your use of the Site, and the privacy practices of PFNCA are subject exclusively to and governed exclusively by the laws of the District of Columbia in the United States. Unless otherwise expressly provided for elsewhere in the terms of service for the Site, to the fullest extent permitted by applicable law, with regard to any dispute between you and PFNCA arising out of this Policy, the Rules, your use of the Site, or the privacy practices of PFNCA, you hereby irrevocably submit to the exclusive jurisdiction of the state and federal courts located therein, waive any right to a trial by jury, and waive any right to claim inconvenient forum. The Site is not intended for use by anyone residing outside the United States of America, and PFNCA is not responsible for any use of or access to the Site by any such person. This Policy is not intended to and shall not be deemed to give you a separate cause of action against PFNCA for breach of this Policy other than liability that is mandated under applicable privacy laws.</p><br/>
<h2 style=\"margin-bottom: 0rem;\">DO NOT TRACK TECHNOLOGY</h2> 
<p>The Site does not currently take actions to respond to Do Not Track signals. We continue to review new technologies and may adopt a standard once one is created.</p><br/>
<h2 style=\"margin-bottom: 0rem;\">Contact Us</h2> 
<p>For questions about this Policy or in general, contract us at:</p><br/>
<p>Parkinson Foundation of the National Capital Area (PFNCA)</p>
<p>3570 Olney Laytonsville Rd #490</p>
<p>Olney, MD 20830</p>
<p>(301) 844-6510</p>
<p>Email: pfnca@parkinsonfoundation.org</p>
</div>
`;
}